### ISSUE TITLE
Create cache directory with more suitable permission

### ISSUE THREAD

**Issue by mattfarina** [sdboyer/vsolver#25]
```go
func NewSourceManager(cachedir, basedir string, force bool, an ProjectAnalyzer) (SourceManager, error) {
	if an == nil {
		return nil, fmt.Errorf("A ProjectAnalyzer must be provided to the SourceManager.")
	}

	err := os.MkdirAll(cachedir, 0777)
	if err != nil {
		return nil, err
	}
```

It's likely not a good idea to use `777` for the cache directory in a multi-user environment. What about `755` instead?

**Comment by sdboyer** [comment]
I think that's the `umask`'s job to decide. This was a quick, throwaway choice, but I [based it on `go get`](https://github.com/golang/go/blob/495e3c60aa61615dd603050ac47f86468f8222b6/src/cmd/go/get.go#L431).

**Comment by sdboyer** [comment]
Closing this, please reopen if deferring to `umask` is not sufficient.
