### ISSUE TITLE
Alias handling?

### ISSUE THREAD

**Issue by mattfarina** [sdboyer/vsolver#26]
In Glide there are two things that complicate handling when they work together.

1. We try to have a global cache of source/vcs.
2. There are aliases. So, a repo of `github.com/mattfarina/vcs` can be used in the location `github.com/Masterminds/vcs`.

So, what happens if one project uses the aliased version and another project uses the normal version and it's in a global cache?

Or, does the cache used in `vsolver` require a per project cache?

And, what happens if someone changes to an alias, possible one that's not a fork, later?

If this is in the code please feel free to point me there. When I was looking I didn't see it.

**Comment by sdboyer** [comment]
I think we may have discussed this one, and this issue predates the discussion, but that's no problem - this kind of aliasing is handled entirely within the solver. The SM deals only with the 'network name', never its intended aliased location. That transformation is [handled by the adapter](https://github.com/sdboyer/vsolver/blob/master/sm_adapter.go#L33-L40).
